### ISSUE TITLE
What the hell is Sketch?

### ISSUE THREAD

**Issue by strataga** [GeekyAnts/NativeBase-Sketch-Template#10]
Just say'n!

**Comment by sanketsahu** [comment]
https://www.sketchapp.com/

**Comment by strataga** [comment]
Yeah, I know. But from README perspective, you can’t tell. Just say’n.

**Comment by sanketsahu** [comment]
@appjitsu Would be great if you can edit and send a pull request! :-)

**Comment by strataga** [comment]
Nah. I’d rather complain… ;)

**Comment by sanketsahu** [comment]
Lol 😉
