### ISSUE TITLE
Sketch library

### ISSUE THREAD

**Issue by hawkins** [GeekyAnts/NativeBase-Sketch-Template#11]
Sketch 47 introduced the feature "[Libraries](https://blog.prototypr.io/everything-about-sketch-47-libraries-419c9095094d)" for collections of symbols, so we could import a library of symbols into an existing project and even get updates to the library.

I don't yet know anything about the technical implementation of these libraries, though. Is it possible to port this template to be a library instead (or in addition to the template), so we can use this along with other templates-turned-libraries as well?

**Comment by hawkins** [comment]
A little more context, having skimmed this, looks like this is up to users to do. Looks like the process goes something like this:

1. Clone repo
2. Add document as a library in our local Sketch
3. Pull changes now and then to see changes reflected in the library

From https://sketchapp.com/docs/libraries/adding-libraries

**Comment by S-Kaushik** [comment]
Hi Josh!

Sorry for taking so long in replying here. Good to know that you found the solution yourself. 😅
We appreciate you sharing this info with everyone. 🙂
