### ISSUE TITLE
Broken link to San Fransisco Fonts

### ISSUE THREAD

**Issue by nonameolsson** [GeekyAnts/NativeBase-Sketch-Template#7]
The link from the website to the San Fransisco fonts doesn't work.
<img width="775" alt="screen shot 2017-06-06 at 19 12 49" src="https://user-images.githubusercontent.com/1493018/26856860-2d45e960-4aec-11e7-8951-668b7847682a.png">

[https://developer.apple.com/fonts/downloads/SFUI.zip](https://developer.apple.com/fonts/downloads/SFUI.zip)

**Comment by S-Kaushik** [comment]
Hey Andreas,

Thanks for bringing out this issue. We'll correct that. 
Meanwhile you can get the needed font from here, https://developer.apple.com/fonts/
